sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aaron2905/docker-react .

script:
  - docker run aaron2905/docker-react

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-009660443531'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_i
  secret_access_key: "$AWS_SECRET_KEY"
