sudo: requires
services:
  - docker

before_install:
  - docker build -t aaron2905/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aaron2905/docker-react npm run test -- --coverage
